### ISSUE TITLE
Create blog page

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#125]
Create blog page with similar design to https://www.charitywater.org/stories/ 

(specifically this portion of the page) 
<img width="1031" alt="Screen Shot 2019-10-07 at 2 09 15 PM" src="https://user-images.githubusercontent.com/7344422/66348744-1bfdad80-e90c-11e9-8b71-e0e288e53215.png">

with a list of blog posts with a one sentence summary + picture, then a read more link to take user to a full page with the full blog post plus multiple pictures rendered.

this should be a page for blog posts and pictures for TeacherFund updates.

**Comment by jingwu21** [comment]
Hi, @joelwass. Could I give this a try?

**Comment by joelwass** [comment]
Of course! @jingwu21 it’s a pretty vague issue - so don’t hesitate to break it into multiple PR’s to check in with progress

**Comment by joelwass** [comment]
If you write out some fake data that should work. Here is an example of a page coded out with fake data right now 

https://github.com/teacherfund/TeacherFund_next/blob/master/pages/account.js#L9

**Comment by dreamerchandra** [comment]
I wish to separate 
![](https://user-images.githubusercontent.com/7344422/66348744-1bfdad80-e90c-11e9-8b71-e0e288e53215.png)
this into separate component and use the dynamic route in order to determine the sub-blog post like `/blog/:country` and rerender the same component by supplying different props. The rest of the page stays the same.
If this is the case I would like to create a separate issue for this...

**Comment by nahsiloh** [comment]
Hello! Would love to help. Is this task still available?

**Comment by joelwass** [comment]
This is still a work in process! so feel free to checkout the code, navigate to /blog and hack away!
