### ISSUE TITLE
Figure out where to host images 

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#14]
cdn or compressed within build? 

should we load smaller images on mobile first?

**Comment by korlando7** [comment]
how about host them on s3 and then include mobile, tablet, and desktop image files for each image, thoughts?

**Comment by stripedpajamas** [comment]
Since we are using Now, we could [follow Zeit's lead](https://spectrum.chat/zeit/now/are-static-deployments-a-good-place-to-host-my-image-assets~a9c13c0d-f893-474b-bb11-a0b18a519c92?m=MTUzNzkwODY2NDI4Nw==) and have the assets in their own Now deployment.

The idea would be to make another repo (TeacherFund_assets) and put our images (with all their different sizes) in the repo. Then set that repo up to auto-deploy like this one is with a `now.json` file (maybe alias the deployment to `teacherfund-assets.now.sh` etc). Then point to the assets from our app in this repo.

If this sounds good let me know and I can set it up.

**Comment by korlando7** [comment]
Sounds good to me

**Comment by joelwass** [comment]
What's the advantage of this. the main site loads faster because it's more light weight, but the pictures take longer to load since it's a network request away? or is it advantageous because first paint because much faster and the photos come in asynchronously?

**Comment by stripedpajamas** [comment]
Well I don't think there is a way to avoid images being a network request away -- I'm not sure what is meant by compressing the images in build, but wouldn't the client still need to request the image from the hosting server to display it locally?

There is no advantage to hosting assets with Zeit over S3 besides having 1 place to manage the whole front end instead of splitting it up.

**Comment by joelwass** [comment]
If we don't put images elsewhere, aren't the images by default currently included in the zeit build i.e. not a network request away?

so by introducing a new hosting server, aren't we introducing the latency of fetching said images?

**Comment by stripedpajamas** [comment]
When the app builds, the assets are uploaded alongside the HTML. When a user browses to the website, the HTML loads and the images are requested because they are referenced in the HTML. The browser downloads them at that time from Zeit. 

Moving the assets to a separate deployment has these benefits:
- smaller GH repo size (easier on contributors)
- ability to set granular caching rules for the images (make the browser only request them once ever etc)
- faster web app deployments since we won't upload images

**Comment by stripedpajamas** [comment]
The simplest solution is to leave the assets in this repo and therefore part of this deployment, and we only miss out on a negligible performance bump

**Comment by stripedpajamas** [comment]
Let's leave image handling as is -- assets are in the repo, they get uploaded to Zeit during a deployment, and served from the Zeit CDN. If we encounter issues with this approach down the road, we can open an issue.
