### ISSUE TITLE
make home page mobile friendly

### ISSUE THREAD

**Issue by joelwass** [teacherfund/TeacherFund_next#23]
style up the mobile first styles of the index.js page

**Comment by joelwass** [comment]
this should use taychon styles that are currently being utilized in the rest of the app

make sure this doesn't change the look/feel of the existing desktop version

http://tachyons.io/docs/

**Comment by joelwass** [comment]
This can be done by using chrome dev tools to simulate the site on iphone X

**Comment by vanessanaja** [comment]
Hi Joel,

I'm new to open source and I really love what you're doing with this project. 

This would be my first issue in open source. 

I thought I'd volunteer to work on this since it's been open for a while. It might take me a second as I have to familiarize myself with tachyon but I'm happy to give it a shot.

**Comment by joelwass** [comment]
Awesome! Thank you!

**Comment by stripedpajamas** [comment]
Hi @vanessanaja -- sorry to pull the rug out from under you here, but I was talking to our front end and it appears he's already got most of this task done on his own branch. It makes more sense for him to just finish it up. 

Thanks so much for offering to help out -- feel free to pick up another issue, and we'll try to be vigilant on our end to make sure the assignee is properly set so no wasted effort is expended.

Cheers

**Comment by vanessanaja** [comment]
No problem. Glad it's being worked out :)
